version: 2
jobs:
  live_test:
    docker:
      - image: eklhad/eklhad-web-circleci:0.1
    working_directory: /go/src/github.com/dahlke/eklhad/
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r pip-reqs.txt
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - live_test