version: 2
jobs:
  live_test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r pip-reqs.txt
      - run:
          name: run tests
          command: python3 -m unittest test/*.py
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - live_test